/**
 * Enchantment Engine - Build System Implementation
 */

#include "build_system.hpp"
#include <filesystem>
#include <iostream>
#include <cstdlib>

namespace fs = std::filesystem;

BuildSystem::BuildSystem(const std::string& projectPath)
    : m_building(false)
    , m_cancelled(false)
    , m_progress(0)
{
    m_config.projectPath = projectPath;
    m_config.outputPath = projectPath + "/build";
    m_config.targetName = "game";
    m_config.buildType = "Release";
    m_config.verbose = false;
}

BuildSystem::~BuildSystem() {
}

BuildResult BuildSystem::build() {
    if (m_building) {
        return BuildResult::Failed;
    }
    
    m_building = true;
    m_cancelled = false;
    m_progress = 0;
    
    output("=== Build Started ===");
    output("Project: " + m_config.projectPath);
    output("Target: " + m_config.targetName + ".gbc");
    
    // Find source files
    auto sourceFiles = findSourceFiles();
    output("Found " + std::to_string(sourceFiles.size()) + " source files");
    
    // Compile each source file
    int compiled = 0;
    for (const auto& file : sourceFiles) {
        if (m_cancelled) {
            output("Build cancelled");
            m_building = false;
            return BuildResult::Cancelled;
        }
        
        output("Compiling: " + file);
        if (!compileSource(file)) {
            output("ERROR: Compilation failed for " + file);
            m_building = false;
            return BuildResult::Failed;
        }
        
        compiled++;
        m_progress = (compiled * 100) / sourceFiles.size();
    }
    
    // Link objects
    output("Linking...");
    if (!linkObjects()) {
        output("ERROR: Linking failed");
        m_building = false;
        return BuildResult::Failed;
    }
    
    // Generate ROM
    output("Generating ROM...");
    if (!generateROM()) {
        output("ERROR: ROM generation failed");
        m_building = false;
        return BuildResult::Failed;
    }
    
    output("=== Build Succeeded ===");
    output("Output: " + m_config.outputPath + "/" + m_config.targetName + ".gbc");
    
    m_building = false;
    m_progress = 100;
    return BuildResult::Success;
}

BuildResult BuildSystem::rebuild() {
    output("=== Rebuild Started ===");
    clean();
    return build();
}

BuildResult BuildSystem::clean() {
    output("=== Clean Started ===");
    
    std::string objPath = m_config.projectPath + "/obj";
    std::string buildPath = m_config.projectPath + "/build";
    
    // Remove object files
    if (fs::exists(objPath)) {
        for (const auto& entry : fs::directory_iterator(objPath)) {
            if (entry.path().extension() == ".o") {
                fs::remove(entry.path());
                output("Removed: " + entry.path().string());
            }
        }
    }
    
    // Remove build output
    if (fs::exists(buildPath)) {
        std::string romPath = buildPath + "/" + m_config.targetName + ".gbc";
        if (fs::exists(romPath)) {
            fs::remove(romPath);
            output("Removed: " + romPath);
        }
    }
    
    output("=== Clean Complete ===");
    return BuildResult::Success;
}

void BuildSystem::cancel() {
    m_cancelled = true;
}

void BuildSystem::setConfig(const BuildConfig& config) {
    m_config = config;
}

BuildConfig BuildSystem::getConfig() const {
    return m_config;
}

void BuildSystem::setOutputCallback(OutputCallback callback) {
    m_outputCallback = callback;
}

bool BuildSystem::isBuilding() const {
    return m_building;
}

int BuildSystem::getProgress() const {
    return m_progress;
}

std::string BuildSystem::getStatus() const {
    return m_status;
}

bool BuildSystem::compileSource(const std::string& file) {
    std::string objFile = getObjectFile(file);
    std::string command = "lcc -c -o \"" + objFile + "\" \"" + file + "\"";
    
    if (m_config.verbose) {
        output(command);
    }
    
    return system(command.c_str()) == 0;
}

bool BuildSystem::linkObjects() {
    auto sourceFiles = findSourceFiles();
    std::string objects;
    
    for (const auto& file : sourceFiles) {
        objects += "\"" + getObjectFile(file) + "\" ";
    }
    
    std::string output = m_config.outputPath + "/" + m_config.targetName + ".gbc";
    std::string command = "lcc -o \"" + output + "\" " + objects;
    
    if (m_config.verbose) {
        this->output(command);
    }
    
    return system(command.c_str()) == 0;
}

bool BuildSystem::generateROM() {
    // ROM is generated by lcc during linking
    std::string romPath = m_config.outputPath + "/" + m_config.targetName + ".gbc";
    return fs::exists(romPath);
}

void BuildSystem::output(const std::string& message) {
    m_status = message;
    std::cout << message << std::endl;
    
    if (m_outputCallback) {
        m_outputCallback(message);
    }
}

std::vector<std::string> BuildSystem::findSourceFiles() {
    std::vector<std::string> files;
    std::string srcPath = m_config.projectPath + "/src";
    
    if (!fs::exists(srcPath)) {
        return files;
    }
    
    for (const auto& entry : fs::recursive_directory_iterator(srcPath)) {
        if (entry.is_regular_file() && entry.path().extension() == ".c") {
            files.push_back(entry.path().string());
        }
    }
    
    return files;
}

std::string BuildSystem::getObjectFile(const std::string& sourceFile) {
    fs::path source(sourceFile);
    std::string objPath = m_config.projectPath + "/obj";
    
    // Create obj directory if it doesn't exist
    if (!fs::exists(objPath)) {
        fs::create_directories(objPath);
    }
    
    return objPath + "/" + source.stem().string() + ".o";
}
